### ISSUE TITLE
Issues with Vagrant 1.6

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-notify#17]
https://github.com/mitchellh/vagrant/issues/3725

**Comment by Driklyn** [comment]
@fgrehm Just to let you know, we're now successfully using `notify-send-http` in our Vagrant / CentOS guest / Mac host local dev environment.

`vagrant-notify` worked initially, but only if you installed the plugin after `vagrant up` (with Chef) finished executing. If the plugin was installed already and you tried to run `vagrant up`, it would either error out with "The SSH connection was unexpectedly closed by the remote end" or break the shared folders between Vagrant and your OS.

And if you tried doing a `vagrant destroy` then `vagrant up` for a fresh instance (with the plugin already installed), the `vagrant up` command would never successfully execute because the plugin would fail after trying to SSH into the VM after only one attempt and stop `vagrant up` from executing further... However, on the first attempt, the VM is always still booting up and not yet ready to go. It typically takes about 3 attempts for SSH access to work for me personally.

I did manage to use `vagrant-notify` for a few days just fine, but then all these issues started appearing and prompted me to switch to `notify-send-http` instead -- which I'd say is even nicer since it doesn't require you to install it as a Vagrant plugin (which, btw, didn't work in Vagrant 1.6.3 -- had to upgrade to the latest: 1.7.2).

Anyways... thanks for all your hard work! Much appreciated.

**Comment by fgrehm** [comment]
Thanks for reporting!

**Comment by nrwiersma** [comment]
As a pre warning I don't really know ruby and I have never made a vagrant plugin.

That being said I was having this issue and dug into it a little and found that if you change plugin.rb line 16 to hook VagrantPlugins::ProviderVirtualBox::Action::WaitForCommunicator rather than VagrantPlugins::ProviderVirtualBox::Action::Boot it seems to stop the issue of first boot failing and it still seems to send notifications.

Maybe that helps?

**Comment by hardyoyo** [comment]
How very odd. I was successfully using the vagrant-notify plugin with Vagrant 1.6.5 on Linux Mint 17 (pretty much just Ubuntu Trusty 64), but after I upgraded to Vagrant 1.7.2, I ran into many issues with shared folders, and I also noticed that vagrant-notify was no longer working 100%... it still worked for provisioning notifications, however, when running notify-send from the guest, no messages were sent. I have now successfully tested notify-send-http, and that seems to work fine. Now I have to figure out how to configure my Vagrant-managed VM to actually set up the notify-send-http client. I have uninstalled the vagrant-notify plugin, and will alert my fellow developers that it may cause issues with Vagrant 1.7.2 and shared/synced folders. I would *love* for this functionality to again be wrapped up in a simple Vagrant plugin, it was really nice getting notifications that maven was done compiling on my VM.

**Comment by hardyoyo** [comment]
This plugin is soo much more useful for me as far as getting actual work done goes, I  think I can live without Vagrant 1.7.x, I am going to downgrade back to 1.6.5, and re-install this plugin.

**Comment by lightvision** [comment]
@nrwiersma Your solution work for me like a charm, using debian 8 as host + laravel/homestead as guest. Thank You!

**Comment by alpha01** [comment]
Closing. This is no longer an issue with the new daemon based notification server.
