### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-notify#24]
Hey guys!

Life, as it tends to do, has progressed for me in such a way that I am no longer able to devote time to maintaining this plugin, especially as I no longer use it on a daily basis.

As such, this project has been neglected and I apologize for that. I am hoping there is someone who would be willing to step up and take over maintaining this project so it gets the attention it deserves. If you would like to do so, please respond with a comment explaining a bit about what you would like to do as a maintainer of this project. I'll then add one or more of those users as collaborators.

Cheers!

**Comment by alpha01** [comment]
Hello @fgrehm 

It's been almost a year, and it looks like nobody has stepped up on helping this project. I'm interested on becoming this plugin's maintainer. I rely on the functionally this plugin provides for our internal development notifications. The following are the changes made to my forked vagrant-notify repo devel branch https://github.com/alpha01/vagrant-notify/tree/devel

**Bug Fixes:**
- `vagrant suspend` stops notification server. https://github.com/fgrehm/vagrant-notify/issues/18
- Plugin causes VM boot to fail. https://github.com/fgrehm/vagrant-notify/pull/22

**New features:**
- Notification server runs as a daemon (fork() has been removed so it's compatible with Windows). https://github.com/fgrehm/vagrant-notify/pull/25 [#5](https://github.com/fgrehm/notify-send-http/issues/5) https://github.com/fgrehm/vagrant-notify/issues/14
- Notification server information is displayed each time vagrant is started and halted.
- New plugin command. Ability to view notification status, start, and stop. [CLI](https://gist.github.com/alpha01/9b81caca694a2735e658f978c41600b5)
- New send-notify scripts based on host system (Linux, OS X, and Windows)
- `vagrant suspend/resume` stops/starts notification server respectively.
- Windows support (beta) [#5](https://github.com/fgrehm/notify-send-http/issues/5)

**Enhanced security:**

_MAJOR SECURITY FIX_: Notification server will now only listen localhost (127.0.0.1), this restricts communication to only between the VM and host system. Since the notification server doesn't do proper shell character escaping and the server binds to all active IPs, anyone using vagrant-notify version 0.4.0 and below is vulnerable to remote command execution.

**Known Issues:**

- Running `vagrant destroy` on an active guest fails stop the notification server.
- On rare occasions the notification server may stop receiving notifications if the host is suspended/hibernates. The notification may need to be manually restarted if that's the case. `vagrant notify --restart`

**Things To Do:**

- Ensure plugin also works with FreeBSD and Solaris guest VMs.
- Add VMWare provider support


I still need to write new/update rpecs unit tests related to these newly changes before submitting a pull request. Let me know what do you think.

-Tony

**Comment by fgrehm** [comment]
WOW! Thats a lot of great work! Thanks a lot for putting this together. Yeah, feel free to open a PR once you feel like it is ready and I'll give you the needed superpowers so you can keep the project going! :metal: 🍻
