### ISSUE TITLE
Does not work with hashcorp/precise64

### ISSUE THREAD

**Issue by scott-cornwell** [fgrehm/vagrant-notify#26]
There is no notify-send on this VM, so it does nothing. Any way to call manually?

**Comment by tony-ten** [comment]
Can you explain your problem with more details? 
It's not necessary for notify-send (libnotify-bin package) to be installed on the VM, since vagrant-notify works by copying over a [script.](https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb)  on the VM. 

See [demo](https://github.com/fgrehm/vagrant-notify#demo) to see how to test it manually. If it doesn't work, ensure the notify server is running on your host system.
`ps aux |grep vagrant-notify`

**Comment by alpha01** [comment]
Closing. Six months after and no additional information provided.
