### ISSUE TITLE
notify-send cannot use custom notifier

### ISSUE THREAD

**Issue by eli007** [fgrehm/vagrant-notify#29]
I wrote my own notification center app that has more going on under the hood than the terminal-notifier script.

How can I get notify-send from the guest VM to send the message back to my own app?

notify-send "message" -> my-app --message "message"

**Comment by alpha01** [comment]
You will have to create a script named `notify-send` and have it be available in your $PATH. 
```bash
#!/bin/bash
my-app  --message "$*"
````

This is because the call to `notify-send` is hard coded onto the notification server https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb#L44


Checkout the examples [scripts](https://github.com/fgrehm/vagrant-notify/tree/master/examples) that are fully compatible with notify-send.
