### ISSUE TITLE
Doesn't listen on all addresses?

### ISSUE THREAD

**Issue by ibrahima** [fgrehm/vagrant-notify#30]
Hi, this plugin is a really great idea! One issue I had was that it looks like by default the server listens on 127.0.0.1, but if my guests are connected on a different interface (eg. with address 10.0.3.1 for lxc), they can't connect and get "Connection refused" when trying to connect. I tried fiddling with iptables and then finally just set the listen address to 0.0.0.0 and that worked, but I assume if this plugin works for other people I might be doing something wrong?

My guest is a vagrant-lxc guest, so I wonder if that has something to do with it.

Any help is appreciated. Thanks!

**Comment by alpha01** [comment]
Hi @ibrahima 

The current release lease of vagrant-notify only works with VirtualBox. I've recently committed support for LXC on the master branch, but haven't had the time to iron out some other enhancements, so I haven't cut a new release yet. 

Currently, if you want vagrant-notify to work with your LXC containers. You can either build a gem from the current master branch or modify your existing notification server to bind to 10.0.3.1 instead of 127.0.0.1.  See https://github.com/fgrehm/vagrant-notify/blob/v0.5.1/lib/vagrant-notify/server.rb#L14

**Comment by ibrahima** [comment]
Oh wow, thanks for the quick response! I've just modified my locally installed gem for now, that works for me.

**Comment by alpha01** [comment]
Awesome.

**Comment by alpha01** [comment]
By the way, I forgot to mentioned this earlier, but for security reasons I highly discourage the use of binding the server to 0.0.0.0. This is because the notification server doesn't have any sort of authentication and running it in a network accessible IP can lead your system vulnerable to remote command execution.
