### ISSUE TITLE
vagrant-notify-0.5.6/lib/vagrant-notify/config.rb:31: warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by MekDrop** [fgrehm/vagrant-notify#40]
New Vagrant comes with Ruby 2.4 and from there comes new warning

https://github.com/fgrehm/vagrant-notify/blob/2075719cae55c7474616386d710d808e95c79158/lib/vagrant-notify/config.rb#L31

From what I understand possible fix for this issue can be ```@bind_ip.is_a?(Integer)``` however I'm not sure why here such type check is needed.

**Comment by alpha01** [comment]
I believe added this check originally when vagrant-notify was only supported in VirtualBox. Thanks for the heads up about this warning. This check is not really needed since `@bind_ip` is set with default values, and even if it's overridden in the Vagrantfile, the `Resolv::IPv4::Regex` condition should be the only thing verifying that the IP is valid.

**Comment by Fuxy22** [comment]
I just ran into the same warning

**Comment by alpha01** [comment]
This issue has been fixed on 0.6.0.
