### ISSUE TITLE
Some *nix like boxes has restrictions for modifying system files and vagrant-notify fails in such scenarios

### ISSUE THREAD

**Issue by MekDrop** [fgrehm/vagrant-notify#41]
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv /tmp/notify-send /usr/bin/notify-send && chmod +x /usr/bin/notify-send

Stdout from the command:



Stderr from the command:

mv: rename /tmp/notify-send to /usr/bin/notify-send: Operation not permitted
```
This is how such error message looks.

These are steps to reproduce such scenario (this one works only with VirtualBox provider!):
1. `vagrant init http://files.dryga.com/boxes/osx-sierra-0.3.1.box`
2. `vagrant up`

I think if command fails in such scenarios, error at least must be more user friendly or in best case scenario no such error should be shown.

**Comment by alpha01** [comment]
Guest's need `sudo` and `ruby` in order for vagrant-notify to work. The plugin already displays a warning if ruby is not installed. I can do the same in case `notify-send` fails to install on the guest, and have it display a warning like this:
`vagrant-notify:  notify-send failed to install on $GUEST_NAME because user doesn't have sudo access.`

With the message being just a warning, the guest system will continue to start up normally instead of failing entirely because of botched notify-send install.

**Comment by MekDrop** [comment]
Yeah that would be great.

For my example box problem is that client has sudo access but it is not enough when you are running on MacOS X because this OS by default protects some paths. Macports and brew I think for same reason installs all package to /usr/local/bin. And `mv /tmp/notify-send /usr/local/bin/notify-send` works without problem. Still ruby is needed for this situation but atleast it is possible to upload notify-send app to guest.

**Comment by alpha01** [comment]
0.6.0 will now display a warning if it's unable to install notify-send on the vagrant box.
